### ISSUE TITLE
Sync Mandates

### ISSUE THREAD

**Issue by Amiir-Dev** [vandarpay/cashier#7]
Get and sync all business mandates  and store in the cashier database

**Comment by WiGeeky** [comment]
After a discussion with Vandar Direct Debit Development Team, it has been deemed for cashier not to be able to sync all mandates at once as this will put a large amount of pressure on our APIs, solutions will instead be released on the API side to make sure our merchants receive updates on mandates.

This should be considered in the future development of Cashier and Vandar product development.
